val df = spark.read.option("delimiter","^").option("header","true").csv("datasets/optd_por_public_all.csv")
df.write.format("delta").save("datasets/optd_por_public_all.delta")
df.write.format("parquet").save("datasets/optd_por_public_all.parquet")
df.withColumn("part", substring(col("geoname_id"), 1,3)).write.format("parquet").partitionBy("part").save("datasets/optd_por_public_all.parquetpartitioned")
df.withColumn("part", col("geoname_id")).write.format("parquet").partitionBy("part").save("datasets/optd_por_public_all.parquetpartitioned2")
